### ISSUE TITLE
Adapt combat tracker to Midgard style

### ISSUE THREAD

**Issue by Byroks** [Byroks/foundry-vtt-system-midgard5#16]
Goal:
  The Combat tracker should be adapted do either show or notify the players which pase currently is happening.
  One combat round in Midgard is divided into Movement and Action Phases. First every Character does their movment in order of initative and after that they do their action in order of initative.
 Your initative is halfed if you moved more than half your Bewegungsweite in the movement phase. (Optional Goal)

**Comment by LeFrique** [comment]
At the moment I use Monks Combat Details for showing who is pacing next on the Canvas. I have some nice free token frames for something like that. 

I also have struggled with the Midgard Combat Details but had the idea to implement a second initiative roll like in the Combat Tracker Enhancement Modul only for the Movement Phase with the highest value for Anführen Skill in the separated fractions Friendly, Neutral, Enemy and let the Gw sort automatically, best after movement with effects from movement. 

If Canvas Movement could be accessible it would be also nice to block spell casting for magic users when moved more than 1m.

I've watched a good video a few weeks ago, have to link it here later.
