### ISSUE TITLE
Some unlearned Skills can be selected multiple times

### ISSUE THREAD

**Issue by LeFrique** [Byroks/foundry-vtt-system-midgard5#33]
These are only the following 3 and could be handled manually with a new item skill from the compenium if this is to hard to implement.
- Abrichten (for the individual animal types)
- Landeskunde (for the individual regions and countries)
- Musizieren (for the individual instruments)

**Comment by Byroks** [comment]
How it is handled right now is through the name of the skill, so as soon you change the name of a learned skill from "Abrichten" to "Abrichten Pferd" for example, the base skill Abrichten is back in the unlearned group.
I will close this issue as it's not really a bug.
