### ISSUE TITLE
Add currency management

### ISSUE THREAD

**Issue by oskaloq** [Byroks/foundry-vtt-system-midgard5#37]
No currency management (GS, SS, KS) available. No cost attributes for gear.

**Comment by LeFrique** [comment]
I'd like to put the currencies in a first step above the EP, GG section in a first step.

Also I want them to count automatically from KS over SS to GS.

In another step I think about adding the Hort for Dwarves only in the same row but hidden and only shown for dwarves when selected as race. 

An enhancement should be to count money for gear in an additional field for the items gear, weapons & defWeapons.

An option for the SL to share money to the players would be nice, perhaps with macro. 

Don't know how much I can do on my own, so assistance will be appreciated.
