### ISSUE TITLE
Add quantity attribute to  gear items

### ISSUE THREAD

**Issue by oskaloq** [Byroks/foundry-vtt-system-midgard5#38]
If the same gear item is dragged into the inventory twice, the items are listed separately. This could be a problem with a larger amount of items like arrows or something like that. So a quantity attribute could help.

**Comment by Byroks** [comment]
I would like to keep two items seperate if they got dragged in individualy

What we can do is add a "Anzahal" field to general items so we can track how many arrows you have for example
Browny points if the field is edditable without opening the item for easier tracking

**Comment by oskaloq** [comment]
That sounds like a very good compromise. Would it then make sense to mark such items with a number as "consumables"? This would possibly simplify automatisms later on: e.g. if you use a consumable (e.g. healing potion) then -1 number. If you use another item (e.g. healing amulet) then no deduction.

**Comment by Byroks** [comment]
That's a great idea, would go hand in hand with creating a Consume button!
Could you create an issue for that and someone can take care at some point
